### ISSUE TITLE
About paper submission

### ISSUE THREAD

**Issue by jenlindadsouza** [umanlp/tg2019task#10]
Dear organizers,

Is the paper submission deadline also according to the AOE timezone on August 19th?

And can we include author names on the paper, or is it a blind review process?

Thank you very much.

**Comment by dustalov** [comment]
Hello and thank you for your contribution! The shared task paper authors can reveal their identities because they are already known due to their participation. The timezone is AoE, but we could extend the deadline. I will post an update here in case of this.

**Comment by dustalov** [comment]
I think it is safe to extend the deadline for the shared task authors till August 23, 2019 (AoE timezone).
