### ISSUE TITLE
Is a python evaluation script with group wise metrics available?

### ISSUE THREAD

**Issue by pratyay-banerjee** [umanlp/tg2019task#5]
I was just curious is there a python evaluation script with group-wise metrics already available?

**Comment by pratyay-banerjee** [comment]
And I dont see any public submissions, is there a different leaderboard?

**Comment by dustalov** [comment]
The available Python script is the same as the on used on CodaLab for grading the submissions, so no other metrics are reported.

The only leaderboard is available at <https://competitions.codalab.org/competitions/20150>, but the participants are not required to mark their submissions as public.

**Comment by dustalov** [comment]
The available Python script is the same as the one used on CodaLab for grading the submissions, so no other metrics are reported.

The only leaderboard is available at <https://competitions.codalab.org/competitions/20150>, but the participants are not required to mark their submissions as public.

**Comment by pratyay-banerjee** [comment]
@dustalov : Thanks. I had few more queries, is there a minimum baseline cut off over MAP for system acceptance ? I have seen those in few workshops being pre-defined, or will it be decided post paper submission ?  And the last query is regarding the length of system description papers : 4 + 1 with references ?

**Comment by dustalov** [comment]
We are providing two baselines. One is a trivial tf-idf baseline for getting started with the task, cf. the [Python](https://github.com/umanlp/tg2019task#python) section of the repository description. It is simple, but demonstrates a very small MAP of 0.05 on the development dataset (Practice phase on [CodaLab](https://competitions.codalab.org/competitions/20150)). Another one is a tf-idf baseline implemented in [Scala](https://github.com/cognitiveailab/explanationreconstructiontextgaphs2019) that uses SVM<sup>rank</sup>, which demonstrates the MAP of 0.28 on the same dataset. I think it is fine to improve even slightly over the Scala baseline.

When submitted the paper, please follow the instructions from the workshop website: <https://sites.google.com/view/textgraphs2019>. We welcome long (8+) and short (4+) papers formatted as according to the ACL style. The choice is up to you.

**Comment by pratyay-banerjee** [comment]
Thanks for the info. I am closing this issue.
