### ISSUE TITLE
No response when submitting to CodaLab

### ISSUE THREAD

**Issue by ameyagodbole** [umanlp/tg2019task#7]
I tried submitting to CodaLab under evaluation. But there is no response from the website. From my perspective, nothing is happening. Is there a time gap between submission and it showing up on the leaderboard/"my submissions"?

Thanks

**Comment by dustalov** [comment]
Our evaluation program outputs the score almost immediately. I can confirm that CodaLab did not process my recent test submissions to both Practice and Evaluation phases. This is not good.

However, I cannot find your submissions. What is your username? How did you submit the results? A received submission should look like in the picture below.

![CodaLab Submission Example](https://user-images.githubusercontent.com/40397/62563682-2e1b8b00-b88c-11e9-9d03-0860aa3c1b8d.png)

**Comment by dustalov** [comment]
Our evaluation program outputs the score almost immediately. I can confirm that CodaLab did not process my recent test submissions to both Practice and Evaluation phases: <https://competitions.codalab.org/competitions/20150>. This is not good.

However, I cannot find your submissions. What is your username? How did you submit the results? A received submission should look like in the picture below.

![CodaLab Submission Example](https://user-images.githubusercontent.com/40397/62563682-2e1b8b00-b88c-11e9-9d03-0860aa3c1b8d.png)

**Comment by dustalov** [comment]
I filed an issue to CodaLab, but I think this is a temporary system-wide issue.

**Comment by PeterAJansen** [comment]
I have also noticed issues connecting to Codalab from the links on the main TextGraphs shared task webpage as of yesterday.  I think they may be having another system-wide breakdown. :(

**Comment by ameyagodbole** [comment]
@dustalov I am in the same stage as you (with the submitted status). Earlier I wasn't even seeing that but I think it was just a matter of patience. Most likely, the zip was being uploaded in the background, but there was no indication of the same on the website.

Just to clarify, the zip file contains the predict.txt file (in the root of the zip archive, not inside another directory)

**Comment by dustalov** [comment]
Yep, now I see your submission. As according to their response (codalab/codalab-competitions#2668), the queue is currently full. Let us wait and keep the fingers crossed!

**Comment by ameyagodbole** [comment]
Just to close this issue, the submission took about 4-5 hours to transition from "submitted" to "finished". It might be good to give this disclaimer to all participants.

Thanks @dustalov
