### ISSUE TITLE
TextGraphs 2019 Shared Task Final Results

### ISSUE THREAD

**Issue by dustalov** [umanlp/tg2019task#8]
Since the evaluation period ends this Friday which is August, 9, 2019, we need to gather the final results of the shared task. The [simplest tf-idf baseline](https://github.com/umanlp/tg2019task#python) shows MAP=0.067687, yet a more [sophisticated SVM<sup>rank</sup> tf-idf baseline](https://github.com/cognitiveailab/explanationreconstructiontextgaphs2019) shows MAP=0.296241.

If your approach either outperforms these baselines or uses a very different methodology, this is a great reason to submit the system description paper to the TextGraphs workshop: <https://sites.google.com/view/textgraphs2019/>.

@ameyagodbole, @jenlindadsouza, @pratyay-banerjee: could you please make your selected submissions public by Friday, so we can finalize the task?

@PeterAJansen: is your MAP number for the Scala-based baseline the same?

**Comment by jenlindadsouza** [comment]
@dustalov May I ask if the scores reported in the quoted sentence below are on the Dev set?

> The simplest tf-idf baseline shows MAP=0.067687, yet a more sophisticated SVMrank tf-idf baseline shows MAP=0.296241.

For the submission that we participants make public, that'll be the scores on the Test set? Since the earlier submissions were lost with Codalab server issues, we at the moment, don't have any submissions on Dev set uploaded.

Thank you for help with clarifications.

**Comment by PeterAJansen** [comment]
I am showing the Scala tf.idf baseline for the masked test set at 0.296 MAP.  I've submitted this to the leaderboard, which (right now) looks to be the only public score visible: 

https://competitions.codalab.org/competitions/20150#results

**Comment by pratyay-banerjee** [comment]
I have published my score.

**Comment by PeterAJansen** [comment]
0.41 is a very substantial improvement on this challenging dataset.  Well done!

**Comment by dustalov** [comment]
> @dustalov May I ask if the scores reported in the quoted sentence below are on the Dev set?

@jenlindadsouza: the development dataset is used for practice only.

The final results are only based on the test dataset that corresponds to the Evaluation phase on CodaLab: <https://competitions.codalab.org/competitions/20150>. Just pick one submission and submit it to the leaderboard to make it public.

**Comment by dustalov** [comment]
Just a small note for everyone. You do not have to submit to the leaderboard immediately. Since the deadline is Friday and assuming the [AoE](https://www.timeanddate.com/time/zones/aoe) timezone (UTC-12), there is still some time for model selection.

**Comment by dustalov** [comment]
After investigating issue #9, I have re-run every submission in every phase. Although it should not change the scores, it provided more detailed error messages for the misformatted datasets.

**Comment by dustalov** [comment]
After investigating issue #9, I have re-run every submission in every phase. Although it should not change the scores, it provided more detailed error messages for the misformatted datasets.

There is less than 17 hours left—we are almost at the finish line!

**Comment by dustalov** [comment]
I think everything is done. Thank you very much for your contribution! We are looking forward to welcoming your participation report papers at the TextGraphs 2019 workshop!
